#include "mnemonics.h"

char* eyreMnemonicNames[MNEMONIC_COUNT] = {
	"add", "or", "adc", "sbb", 
	"and", "sub", "xor", "cmp", 
	"push", "pop", "movsxd", "movsx", 
	"movzx", "insb", "insw", "insd", 
	"outsb", "outsw", "outsd", "ja", 
	"jae", "jb", "jbe", "jc", 
	"je", "jg", "jge", "jl", 
	"jle", "jna", "jnae", "jnb", 
	"jnbe", "jnc", "jne", "jng", 
	"jnge", "jnl", "jnle", "jno", 
	"jnp", "jns", "jnz", "jo", 
	"jp", "jpe", "jpo", "js", 
	"jz", "test", "xchg", "mov", 
	"lea", "nop", "cbw", "cwde", 
	"cdqe", "cwd", "cdq", "cqo", 
	"wait", "fwait", "pushf", "pushfq", 
	"lahf", "movsb", "movsw", "movsd", 
	"movsq", "cmpsb", "cmpsw", "cmpsd", 
	"cmpsq", "stosb", "stosw", "stosd", 
	"stosq", "scasb", "scasw", "scasd", 
	"scasq", "lodsb", "lodsw", "lodsd", 
	"lodsq", "rol", "ror", "rcl", 
	"rcr", "sal", "shl", "shr", 
	"sar", "ret", "retf", "leavew", 
	"leave", "int3", "int", "int1", 
	"iretw", "iretd", "iretq", "jcxz", 
	"jrcxz", "in", "out", "hlt", 
	"cmc", "not", "neg", "mul", 
	"imul", "div", "idiv", "clc", 
	"stc", "cli", "sti", "cld", 
	"std", "inc", "dec", "call", 
	"callf", "jmp", "jmpf", "rdrand", 
	"rdseed", 
};
